-- MySQL Script generated by MySQL Workbench
-- Fri Sep 22 10:14:05 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`cidadao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cidadao` (
  `id_cidadao` INT NOT NULL,
  `nome` VARCHAR(90) NOT NULL,
  `idade` CHAR(2) NOT NULL,
  `genero` VARCHAR(9) NOT NULL,
  `cpf` CHAR(11) NOT NULL,
  `etnia` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(250) NOT NULL,
  `bairro` VARCHAR(50) NOT NULL,
  `cidade` VARCHAR(50) NOT NULL,
  `cep` CHAR(9) NOT NULL,
  `casa_propria` TINYINT NOT NULL,
  `telefone1` CHAR(11) NOT NULL,
  `telefone2` CHAR(11) NULL,
  PRIMARY KEY (`id_cidadao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empresa` (
  `id_empresa` INT NOT NULL,
  `cnpj` CHAR(13) NOT NULL,
  `razao_social` VARCHAR(90) NOT NULL,
  `nome_fantasia` VARCHAR(90) NOT NULL,
  `ramo_de_atividade` VARCHAR(90) NOT NULL,
  `endereco` VARCHAR(250) NOT NULL,
  `bairro` VARCHAR(50) NOT NULL,
  `cidade` VARCHAR(50) NOT NULL,
  `cep` CHAR(9) NOT NULL,
  `telefone1` CHAR(11) NOT NULL,
  `telefone2` CHAR(11) NULL,
  `email` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_empresa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`agente_publico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`agente_publico` (
  `id_apublico` INT NOT NULL,
  `nome` VARCHAR(250) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `etnia` VARCHAR(45) NOT NULL,
  `esfera` VARCHAR(45) NOT NULL,
  `tipo_doacao` VARCHAR(45) NOT NULL,
  `valor_doacao` FLOAT NOT NULL,
  `descricao_adoacao` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id_apublico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`servico` (
  `id_servico` INT NOT NULL,
  `descricao` VARCHAR(250) NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  `nome_responsavel` VARCHAR(250) NOT NULL,
  `quantidade` INT NOT NULL,
  `data_inicial` DATE NOT NULL,
  `date_final` DATE NOT NULL,
  PRIMARY KEY (`id_servico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cidadao_has_servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cidadao_has_servico` (
  `cidadao_id_cidadao` INT NOT NULL,
  `servico_id_servico` INT NOT NULL,
  PRIMARY KEY (`cidadao_id_cidadao`, `servico_id_servico`),
  INDEX `fk_cidadao_has_servico_servico1_idx` (`servico_id_servico` ASC) VISIBLE,
  INDEX `fk_cidadao_has_servico_cidadao_idx` (`cidadao_id_cidadao` ASC) VISIBLE,
  CONSTRAINT `fk_cidadao_has_servico_cidadao`
    FOREIGN KEY (`cidadao_id_cidadao`)
    REFERENCES `mydb`.`cidadao` (`id_cidadao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cidadao_has_servico_servico1`
    FOREIGN KEY (`servico_id_servico`)
    REFERENCES `mydb`.`servico` (`id_servico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`agente_publico_has_servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`agente_publico_has_servico` (
  `agente_publico_id_apublico` INT NOT NULL,
  `servico_id_servico` INT NOT NULL,
  PRIMARY KEY (`agente_publico_id_apublico`, `servico_id_servico`),
  INDEX `fk_agente_publico_has_servico_servico1_idx` (`servico_id_servico` ASC) VISIBLE,
  INDEX `fk_agente_publico_has_servico_agente_publico1_idx` (`agente_publico_id_apublico` ASC) VISIBLE,
  CONSTRAINT `fk_agente_publico_has_servico_agente_publico1`
    FOREIGN KEY (`agente_publico_id_apublico`)
    REFERENCES `mydb`.`agente_publico` (`id_apublico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agente_publico_has_servico_servico1`
    FOREIGN KEY (`servico_id_servico`)
    REFERENCES `mydb`.`servico` (`id_servico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`empresa_has_servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empresa_has_servico` (
  `empresa_id_empresa` INT NOT NULL,
  `servico_id_servico` INT NOT NULL,
  PRIMARY KEY (`empresa_id_empresa`, `servico_id_servico`),
  INDEX `fk_empresa_has_servico_servico1_idx` (`servico_id_servico` ASC) VISIBLE,
  INDEX `fk_empresa_has_servico_empresa1_idx` (`empresa_id_empresa` ASC) VISIBLE,
  CONSTRAINT `fk_empresa_has_servico_empresa1`
    FOREIGN KEY (`empresa_id_empresa`)
    REFERENCES `mydb`.`empresa` (`id_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empresa_has_servico_servico1`
    FOREIGN KEY (`servico_id_servico`)
    REFERENCES `mydb`.`servico` (`id_servico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
